[tool.poetry]
authors = ["Guillaume Gauvrit <guillaume@gauvr.it>"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Framework :: AsyncIO",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: BSD License",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Topic :: Internet :: WWW/HTTP",
]
description = "A circuit breaker implementation for asyncio"
homepage = "https://github.com/mardiros/purgatory"
license = "BSD-derived"
name = "purgatory"
packages = [
  {include = "purgatory", from = "src"},
]
readme = "README.rst"
version = "1.0.1"

[tool.pyright]
include = ["src"]
typeCheckingMode = "strict"

[[tool.mypy.overrides]]
module = "purgatory.*"
disallow_untyped_defs = true
disallow_any_generics = true

[tool.poetry.dependencies]
python = "^3.7"
aioredis = {version = "^2.0.1", optional = true}
redis = {version = "^4.1.0", optional = true}

[tool.poetry.extras]
aioredis = ["aioredis"]
redis = ["redis"]

[tool.poetry.dev-dependencies]
black = "^22.3.0"
coverage = {version = "^6.2", extras = ["toml"]}
flake8 = "^4.0.1"
isort = "^5.9.3"
pytest = "^7.1.2"
pytest-asyncio = "^0.18.3"
pytest-cov = "^3.0.0"
aioredis = "^2.0.1"
Sphinx = "^4.3.2"
sphinx-rtd-theme = "^1.0.0"
tomlkit = "^0.11.0"
unasync = "^0.5.0"
redis = "^4.1.0"
mypy = "^0.960"
typing-extensions = "^4.0.1"
types-redis = "^4.1.8"
types-setuptools = "^57.4.7"

[tool.isort]
profile = "black"

[tool.coverage.report]
exclude_lines = [
  "except ImportError:",
  "except pkg_resources.DistributionNotFound:",
]

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
