
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-25T08:03:02+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "6463e9b180bddcb88548da5beb7bc6c4a12c5597",
 "version": "0.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
