[build-system]
requires = ["setuptools>=58", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 120
target-version = ["py37", "py38", "py39", "py310"]

[tool.isort]
profile = "black"
line_length = 120
multi_line_output = 3

[tool.mypy]
files = "pytest_bdd/**/*.py"
python_version = "3.7"
show_error_codes = true
warn_return_any = true
warn_unused_configs = true

[[tool.mypy.overrides]]
module = ["attr.*", "gherkin.*", "mako.*", "ordered_set", "parse", "parse_type.*", "pluggy.*"]
ignore_missing_imports = true
