[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.4,<4", "setuptools_scm"]

[project]
name = "grnkit"
authors = [
    { name = "Hao Zhu" }
]
maintainers = [
    { name = "Hao Zhu", email = "haozhu233@gmail.com" }
]
license = {file = "LICENSE"}
description = "A kit for running benchmarks on inferencing gene regulatory networks. (under construction)"
version = "0.0.3"
requires-python = ">=3.7"
classifiers = ["License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)"]

dependencies = [
    "numpy>=1.16.5",
    "pandas>=1.1.1",
    "scipy>1.4",
    "h5py>=3",
    "natsort",
    "packaging>=20",
    "anndata",
    "scikit-learn",
    "networkx"
]

[project.urls]
Home = "https://github.com/haozhu233/grnkit"
