# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spaceone/api/spot_automation/plugin/cost_saving.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5spaceone/api/spot_automation/plugin/cost_saving.proto\x12#spaceone.api.spot_automation.plugin\x1a\x1cgoogle/protobuf/struct.proto\"V\n\x11\x43ostSavingRequest\x12\x13\n\x0bresource_id\x18\x01 \x01(\t\x12,\n\x0bsecret_data\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct\"C\n\x0e\x43ostSavingInfo\x12\x31\n\x10\x63ost_saving_info\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct2\x82\x01\n\nCostSaving\x12t\n\x03get\x12\x36.spaceone.api.spot_automation.plugin.CostSavingRequest\x1a\x33.spaceone.api.spot_automation.plugin.CostSavingInfo\"\x00\x62\x06proto3')



_COSTSAVINGREQUEST = DESCRIPTOR.message_types_by_name['CostSavingRequest']
_COSTSAVINGINFO = DESCRIPTOR.message_types_by_name['CostSavingInfo']
CostSavingRequest = _reflection.GeneratedProtocolMessageType('CostSavingRequest', (_message.Message,), {
  'DESCRIPTOR' : _COSTSAVINGREQUEST,
  '__module__' : 'spaceone.api.spot_automation.plugin.cost_saving_pb2'
  # @@protoc_insertion_point(class_scope:spaceone.api.spot_automation.plugin.CostSavingRequest)
  })
_sym_db.RegisterMessage(CostSavingRequest)

CostSavingInfo = _reflection.GeneratedProtocolMessageType('CostSavingInfo', (_message.Message,), {
  'DESCRIPTOR' : _COSTSAVINGINFO,
  '__module__' : 'spaceone.api.spot_automation.plugin.cost_saving_pb2'
  # @@protoc_insertion_point(class_scope:spaceone.api.spot_automation.plugin.CostSavingInfo)
  })
_sym_db.RegisterMessage(CostSavingInfo)

_COSTSAVING = DESCRIPTOR.services_by_name['CostSaving']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COSTSAVINGREQUEST._serialized_start=124
  _COSTSAVINGREQUEST._serialized_end=210
  _COSTSAVINGINFO._serialized_start=212
  _COSTSAVINGINFO._serialized_end=279
  _COSTSAVING._serialized_start=282
  _COSTSAVING._serialized_end=412
# @@protoc_insertion_point(module_scope)
