# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spaceone/api/spot_automation/plugin/history.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1spaceone/api/spot_automation/plugin/history.proto\x12#spaceone.api.spot_automation.plugin\x1a\x1cgoogle/protobuf/struct.proto\"S\n\x0eHistoryRequest\x12\x13\n\x0bresource_id\x18\x01 \x01(\t\x12,\n\x0bsecret_data\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct\"<\n\x0bHistoryInfo\x12-\n\x0chistory_info\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct2y\n\x07History\x12n\n\x03get\x12\x33.spaceone.api.spot_automation.plugin.HistoryRequest\x1a\x30.spaceone.api.spot_automation.plugin.HistoryInfo\"\x00\x62\x06proto3')



_HISTORYREQUEST = DESCRIPTOR.message_types_by_name['HistoryRequest']
_HISTORYINFO = DESCRIPTOR.message_types_by_name['HistoryInfo']
HistoryRequest = _reflection.GeneratedProtocolMessageType('HistoryRequest', (_message.Message,), {
  'DESCRIPTOR' : _HISTORYREQUEST,
  '__module__' : 'spaceone.api.spot_automation.plugin.history_pb2'
  # @@protoc_insertion_point(class_scope:spaceone.api.spot_automation.plugin.HistoryRequest)
  })
_sym_db.RegisterMessage(HistoryRequest)

HistoryInfo = _reflection.GeneratedProtocolMessageType('HistoryInfo', (_message.Message,), {
  'DESCRIPTOR' : _HISTORYINFO,
  '__module__' : 'spaceone.api.spot_automation.plugin.history_pb2'
  # @@protoc_insertion_point(class_scope:spaceone.api.spot_automation.plugin.HistoryInfo)
  })
_sym_db.RegisterMessage(HistoryInfo)

_HISTORY = DESCRIPTOR.services_by_name['History']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HISTORYREQUEST._serialized_start=120
  _HISTORYREQUEST._serialized_end=203
  _HISTORYINFO._serialized_start=205
  _HISTORYINFO._serialized_end=265
  _HISTORY._serialized_start=267
  _HISTORY._serialized_end=388
# @@protoc_insertion_point(module_scope)
