
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-23T17:42:03-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "8c5dbba79864cda0ffb2f49ce5e2e40e0e6877cd",
 "version": "0.5.19"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
