
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-27T20:28:27+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "19956839c008030f1e22484fb313912663a0a7b0",
 "version": "1.39.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
