repos:
  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: detect-private-key
      - id: destroyed-symlinks
      - id: check-symlinks
      - id: debug-statements
      - id: check-toml
      - id: check-yaml
  - repo: https://github.com/flakeheaven/flakeheaven
    rev: 0.11.0
    hooks:
      - id: flakeheaven
        additional_dependencies: [
          flake8,
          flake8-bandit,
          flake8-bugbear,
          flake8-builtins,
          flake8-comprehensions,
          flake8-docstrings,
          flake8-simplify,
          flake8-use-fstring,
          pep8-naming,
        ]
