[tool.poetry]
name = "jamf"
version = "0.1.0"
description = ""
authors = ["Trenten Oliver <trentenoliver@outlook.com>"]

[tool.poetry.dependencies]
python = "^3.10"
httpx = "^0.23.0"
keyring = "^23.5.1"
pydantic = "^1.9.1"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
flake8 = "^4.0.1"
black = "^22.3.0"
mypy = "^0.950"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
