[build-system]
requires = [
    "setuptools>=42",
    "protobuf==3.20.1",
    "python-json-logger==2.0.2",
    "numpy==1.22.3",
    "pillow==9.1.1",
    "boto3==1.23.6",
    "aio_pika==6.8.1",
]
build-backend = "setuptools.build_meta"