
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-24T09:08:34-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "1dbcf37a12b465f69d7fbc70917e9510705aaaa7",
 "version": "2.12.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
