name: Build wheels

# Run workflow on pushes or pull requests that modify the code, workflows, or the
# Python packaging.
# Also run on new releases, and allow manual runs.
on:
  push:
    paths:
      - '.github/workflows'
      - 'src/**'
      - 'setup.*'
      - 'pyproject.toml'
  pull_request:
    paths:
      - '.github/workflows'
      - 'src/**'
      - 'setup.*'
      - 'pyproject.toml'
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  # Note: cibuildwheel configuration comes from pyproject.toml instead of env vars!
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.2.2

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
