from typing import TypeVar

from .EventContainer import EventContainer
from .BaseEvent import BaseEvent
from .EventFallFlying import EventFallFlying
from .EventDisconnect import EventDisconnect
from .EventEXPChange import EventEXPChange
from .EventCustom import EventCustom
from .EventRecvMessage import EventRecvMessage
from .EventHeal import EventHeal
from .EventAirChange import EventAirChange
from .EventBlockUpdate import EventBlockUpdate
from .CodeCompileEvent import CodeCompileEvent
from .EventEntityHealed import EventEntityHealed
from .EventClickSlot import EventClickSlot
from .EventResourcePackLoaded import EventResourcePackLoaded
from .EventDimensionChange import EventDimensionChange
from .EventItemDamage import EventItemDamage
from .EventJoinedTick import EventJoinedTick
from .EventItemPickup import EventItemPickup
from .EventOpenScreen import EventOpenScreen
from .EventDeath import EventDeath
from .EventTitle import EventTitle
from .EventSignEdit import EventSignEdit
from .CommandContextHelper import CommandContextHelper
from .EventSendMessage import EventSendMessage
from .EventTick import EventTick
from .EventSound import EventSound
from .EventOpenContainer import EventOpenContainer
from .EventKey import EventKey
from .EventProfileLoad import EventProfileLoad
from .EventBossbar import EventBossbar
from .EventService import EventService
from .EventEntityLoad import EventEntityLoad
from .EventDamage import EventDamage
from .EventPlayerLeave import EventPlayerLeave
from .EventChunkLoad import EventChunkLoad
from .EventChunkUnload import EventChunkUnload
from .EventHungerChange import EventHungerChange
from .EventDropSlot import EventDropSlot
from .EventArmorChange import EventArmorChange
from .EventRiding import EventRiding
from .EventPlayerJoin import EventPlayerJoin
from .EventEntityUnload import EventEntityUnload
from .EventJoinServer import EventJoinServer
from .EventEntityDamaged import EventEntityDamaged
from .EventHeldItemChange import EventHeldItemChange

File = TypeVar["java.io.File"]

