[tool.poetry]
name = "eomap-models"
version = "0.1.13"
description = ""
authors = ["Luis Coelho"]

[tool.poetry.dependencies]
python = "^3.6"
pydantic = "1.7.3"
geojson-pydantic = "0.3.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
