
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-27T10:21:34+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "6323df1515636d834af32fe6ef9162da7752f7ea",
 "version": "0.0.16rc2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
