
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-24T09:35:44+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "4d2f20f297a492d9cda5aa74836afee28b809ecd",
 "version": "v0.1.27"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
