
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-27T20:52:02+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "cfb7494dbe9545fed5a281554a747e6e1c6fe7ff",
 "version": "0.15.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
