[tool.poetry]
name = "hybrid-garden"
version = "0.1.2"
description = ""
authors = ["Ilona Kovaleva <iloncka.ds@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.7,<3.11"
numpy = "^1.20.0"
scikit-learn = "^1.0.2"
pygad = "^2.16.3"
pmlb = "^1.0.1"
randomname = "^0.1.5"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
ipykernel = "^6.13.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
