[tool.poetry]
name = "kare"
version = "0.0.1"
description = "Minimalist Currying implementation for Python"
authors = ["Francisco J. Jurado <9376816+Beetelbrox@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/Beetelbrox/kare"
repository = "https://github.com/Beetelbrox/kare"
keywords = [
    "functional",
    "functional programming",
    "fp",
    "curry",
    "currying",
]
include = [
    "LICENSE",
]


[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
