[build-system]
requires      = [
    "setuptools>=61.0.0",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "python-ufile"
version = "1.0.0"
description = "Upload/Download from ufile.io with this minimal python sdk."
readme = "README.md"
authors = [{ name = "Aria Bagheri", email = "ariab9342@gmail.com" }]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = ["ufile.io", "upload", "download"]
dependencies = [
    "aiofiles >= 0.8.0",
    "requests >= 2.27.1",
]
requires-python = ">=3.9"

[project.urls]
Homepage = "https://github.com/AriaBagheri/python_ufile"

[tool.bumpver]
current_version = "2022.1001-alpha"
version_pattern = "YYYY.BUILD[-TAG]"
commit_message = "bump version {old_version} -> {new_version}"
commit = true
tag = true
push = true

[tool.bumpver.file_patterns]
"pyproject.toml" = [
    'current_version = "{version}"',
]
"setup.py" = [
    "{version}",
    "{pep440_version}",
]
"README.rst" = [
    "{version}",
    "{pep440_version}",
]

