[tool.poetry]
name = "gelatin_extract"
version = "0.1.0"
description = "XML and JSON deserialization"
authors = ["Parker Hancock <633163+parkerhancock@users.noreply.github.com>"]
license = "Apache Software License 2.0"

[tool.poetry.dependencies]
python = "^3.9"
lxml = "^4.8.0"
python-dateutil = "^2.8.2"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
keyring = "^23.5.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
