[build-system]

requires = [
    "setuptools",
    "wheel",
    "numpy>=1.12",
    "scipy>=0.18",
    "scikit-learn>=0.19.1",
    "pyaml>=16.9",
    "scikit-optimize>=0.9.0",
    "joblib>=0.11",
]