[tool.poetry]
name = "nextc"
version = "0.1"
description = "The Next Programming Language for you."
authors = ["VincentRPS"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
llvmlite = "^0.38.1"
rply = "^0.7.8"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
isort = "^5.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = 'black'

[tool.black]
target-version = ['py310']
skip-string-normalization = true
