[tool.poetry]
name = "frenchbee"
version = "0.1.1"
description = "Python client for finding French Bee airline prices."
authors = ["Kevin Ramdath <krpent@gmail.com>"]
repository = "https://github.com/minormending/frenchbee"
readme = "README.md"
license = "MIT"
keywords = ["frenchbee", "flights", "travel"]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.27.1"
beautifulsoup4 = "^4.11.1"
jsonpath-ng = "^1.5.3"

[tool.poetry.dev-dependencies]
black = "^22.1.0"

[tool.poetry.scripts]
frenchbee-cli = "frenchbee.cli:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
