[project]
name = "better-types"
version = "0.0.1"
description = "Some improved types and tools for Python"
authors = [
    { name = "Axel H.", email = "noirbizarre@gmail.com" },
]
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "more-itertools>=8.13.0",
]

[project.license]
text = "MIT"

[project.optional-dependencies]

[project.urls]
repository = "https://github.com/noirbizarre/better-types"

[tool.pdm.dev-dependencies]
test = [
    "pytest>=7.1.2",
    "pytest-sugar>=0.9.4",
    "coverage[toml]>=6.4",
]
lint = [
    "black>=22.3.0",
    "isort>=5.10.1",
    "flake8>=4.0.1",
    "mypy>=0.960",
]
doc = [
    "sphinx>=4.5.0",
    "sphinx-autobuild>=2021.3.14",
    "sphinx-copybutton>=0.5.0",
    "sphinx-inline-tabs>=2022.1.2b11",
    "myst-parser[linkify]>=0.17.2",
    "furo>=2022.4.7",
]
tox = [
    "tox",
    "tox-pdm",
]

[tool.pdm.scripts]
test = "pytest"
doc = "sphinx-build docs docs/_build/html"
"doc:watch" = "sphinx-autobuild docs docs/_build/html"

[tool.pdm.scripts.lint]
shell = "echo \"Flakes\"\nflakeheaven lint better\n# flake8 better\necho \"isort\"\nisort --check better\necho \"black\"\nblack --check better\necho \"MyPy\"\nmypy better\n"

[tool.pdm.scripts.format]
shell = "isort better\nblack better\n"

[tool.pytest.ini_options]
norecursedirs = ".git build dist __pypackages__"
testpaths = [
    "tests",
    "better",
]
addopts = "--doctest-modules"

[tool.black]
line-length = 100
preview = true
target-version = [
    "py39",
    "py310",
]

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
line_length = 110
force_sort_within_sections = true
known_first_party = [
    "better",
    "tests",
]
forced_separate = [
    "tests",
]
combine_as_imports = true

[tool.mypy]
python_version = "3.9"

[build-system]
requires = [
    "pdm-pep517>=0.12.0",
]
build-backend = "pdm.pep517.api"
