
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-23T13:36:02+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "b563760219258c4708439d7a4ce1b9b26e51677a",
 "version": "1.42"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
