
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-29T22:59:56+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "5618755c28d425a789d05a4a638f2d6118797968",
 "version": "1.0rc3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
