# Generated by Django 3.0 on 2022-03-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0005_auto_20220302_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master_db',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
