# Generated by Django 3.0 on 2022-03-08 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0010_auto_20220308_0605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master_db',
            name='week_end',
        ),
        migrations.RemoveField(
            model_name='master_db',
            name='week_start',
        ),
    ]
