# Generated by Django 3.0 on 2022-03-10 10:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0015_auto_20220308_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='master_db',
            name='week_end',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='master_db',
            name='week_start',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
    ]
