[tool.poetry]
name = "csotools-serverquery"
version = "0.6.0"
description = "Query GoldSource and CSO servers for server info, players and more"
authors = ["AnggaraNothing <anggarayamap@protonmail.com>"]
license = "MIT"
classifiers=[
    "Development Status :: 4 - Beta",
    "Operating System :: OS Independent",
    "Topic :: Games/Entertainment"
]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
