runner:
  flake8:
    cmd: flake8 --ignore=W391,E501,W291,E203,E211,W503,W293,E302,
    level: warning
    format: flake8
  isort-diff:
    cmd: isort ./jijzept --diff
    level: warning
    format: diff
  isort:
    cmd: isort ./jijzept --verbose --show-files --check
    level: info
    format: isort
  mypy:
    cmd: mypy jijzept
    level: warning
    format: mypy
