[tool.poetry]
name = "gobotz_rabbitmq"
version = "0.0.6"
description = "aioamqp wrapper for rabbitmq"
authors = ["David Skeppstedt <david@micronova.se>"]
license = "The Unlicense"

[tool.poetry.dependencies]
python = "^3.10"
aioamqp = "^0.15.0"
build = "^0.8.0"
ujson = "^5.3.0"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
pylama_pylint = "^3.1.1"
pytest = "^7.1.2"
pylint = "^2.13.9"
pylama = "^8.3.8"
build = "^0.8.0"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
