# This file is generated by setup.py. DO NOT EDIT!
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals
version = '0.9.7'
git_version = '0881fec92d1d638c659658d6a6cfccc6b819f3dd'
