[tool.poetry]
name = "secondary"
version = "1.0"
description = "Printing your text(code) in slow mode & handwrite effect."
authors = ["Flame <matixsun1@gmail.com>"]
license = "GPL-v3"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
