[tool.poetry]
name = "pythogen"
version = "0.0.18"
description = ""
repository = "https://github.com/artsmolin/pythogen"
authors = []

[tool.poetry.dependencies]
python = "^3.9"
typer = "^0.4.1"
pyyaml = "^6.0"
jinja2 = "^3.1.1"
rich = "^12.2.0"
inflection = "^0.5.1"
pytest = "^7.1.2"

[tool.poetry.scripts]
pythogen = 'pythogen.entrypoint:run'

[build-system]
requires = ["poetry>=1.1.0"]
build-backend = "poetry.masonry.api"
