# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spaceone/api/billing/v1/billing.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%spaceone/api/billing/v1/billing.proto\x12\x17spaceone.api.billing.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1cgoogle/api/annotations.proto\"\xa3\x02\n\x12\x42illingDataRequest\x12\x14\n\nproject_id\x18\x01 \x01(\tH\x00\x12\x1a\n\x10project_group_id\x18\x02 \x01(\tH\x00\x12\x18\n\x10service_accounts\x18\x03 \x03(\t\x12\'\n\x06\x66ilter\x18\x04 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x13\n\x0b\x61ggregation\x18\x05 \x03(\t\x12\r\n\x05start\x18\x06 \x01(\t\x12\x0b\n\x03\x65nd\x18\x07 \x01(\t\x12\x13\n\x0bgranularity\x18\x08 \x01(\t\x12\x11\n\tdomain_id\x18\t \x01(\t\x12%\n\x04sort\x18\n \x01(\x0b\x32\x17.google.protobuf.Struct\x12\r\n\x05limit\x18\x0b \x01(\x05\x42\t\n\x07project2\x81\x01\n\x07\x42illing\x12v\n\x08get_data\x12+.spaceone.api.billing.v1.BillingDataRequest\x1a\x17.google.protobuf.Struct\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/billing/v1/billing/get-datab\x06proto3')



_BILLINGDATAREQUEST = DESCRIPTOR.message_types_by_name['BillingDataRequest']
BillingDataRequest = _reflection.GeneratedProtocolMessageType('BillingDataRequest', (_message.Message,), {
  'DESCRIPTOR' : _BILLINGDATAREQUEST,
  '__module__' : 'spaceone.api.billing.v1.billing_pb2'
  # @@protoc_insertion_point(class_scope:spaceone.api.billing.v1.BillingDataRequest)
  })
_sym_db.RegisterMessage(BillingDataRequest)

_BILLING = DESCRIPTOR.services_by_name['Billing']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BILLING.methods_by_name['get_data']._options = None
  _BILLING.methods_by_name['get_data']._serialized_options = b'\202\323\344\223\002\036\022\034/billing/v1/billing/get-data'
  _BILLINGDATAREQUEST._serialized_start=127
  _BILLINGDATAREQUEST._serialized_end=418
  _BILLING._serialized_start=421
  _BILLING._serialized_end=550
# @@protoc_insertion_point(module_scope)
