[tool]
[tool.poetry]
name = "pysignalr"
version = "0.1.2"
description = "Modern, reliable and async-ready client for SignalR protocol"
keywords = ["signalr", "asp", "client", "asyncio", "json", "messagepack", "websockets"]
classifiers = [
    "Programming Language :: Python :: 3.8",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
homepage = "https://github.com/dipdup-net/pysignalr"
authors = [
    "Lev Gorodetskiy <github@droserasprout.space>",
    "mandrewcito <anbaalo@gmail.com>"
]
readme = "README.md"

packages = [
    { include = "pysignalr", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.8"
websockets = "10.3"
aiohttp = "^3.7.4"
msgpack = "^1.0.2"

[tool.poetry.dev-dependencies]
black = "^22.1.0"
bump2version = "^1.0.1"
diff-cover = "^5.0.1"
isort = "^5.9.3"
mypy = "^0.910"
pytest = "^6.2.5"
pytest-cov = "^3.0.0"
flake8 = "^3.9.2"
flake8-return = "^1.1.3"
flake8-comprehensions = "^3.8.0"
flake8-bugbear = "^22.1.11"
flake8-simplify = "^0.14.5"
flakehell = "^0.9.0"

[tool.isort]
line_length = 140
force_single_line = true

[tool.black]
line-length = 140
target-version = ['py38']
skip-string-normalization = true

[tool.flakehell]
format = "colored"
max_line_length = 140
show_source = true
extended_default_ignore = []

[tool.flakehell.plugins]
pyflakes = ["+*"]
"flake8-*" = ["+*"]
flake8-docstrings = ["-*"]
flake8-simplify = ["-SIM106"]

[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
