_target_: nlhappy.datamodules.TextPairClassificationDataModule

data_dir: ${data_dir} # data_dir is specified in config.yaml
pretrained_dir: ${pretrained_dir}
dataset: 
plm: 
max_length: 
batch_size: 
return_pair: False
num_workers: 2
pin_memory: True