
name: Tests

on:
  push:
    paths:
      - 'illumio/**'
      - 'tests/**'
      - 'workflows/run-tests.yml'
  pull_request:
    branches:
      - main
      - 'release/**'
    paths:
      - 'illumio/**'
      - 'tests/**'
      - 'workflows/run-tests.yml'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
        os: [ubuntu-18.04, macOS-latest, windows-latest]
        include:
          - python-version: 3.11-dev
            os: ubuntu-latest
            experimental: true

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        make
    - name: Run tests
      run: |
        make ci