
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-26T15:24:36+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "bdf7153a0f4c0b159ec13626b5f8834c95c722f8",
 "version": "0.2.2.post0.dev40"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
