
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-24T10:17:08+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "35d72eedc748ca13b1ecc3067a9e6135c277a25c",
 "version": "7.8.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
