[tool.poetry]
name = "wagtail-ckeditor"
version = "1.0.0"
description = "Rich-text editor for Django Wagtail CMS"
authors = ["penkhasoveg <pen.egor2002@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/ghettoDdOS/pve-utils"
repository = "https://github.com/ghettoDdOS/pve-utils"
keywords = ["wagtail", "django", "ckeditor"]
include = [
    "LICENSE",
]

[tool.black]
line-length = 79

[tool.isort]
multi_line_output=3
include_trailing_comma=true
use_parentheses=true
line_length=79

[tool.flake8]
ignore = ["E231", "W503", "E731"]
max-line-length = 79
exclude="*/migrations/*"

[tool.poetry.dependencies]
python = "^3.7"
wagtail = "^2.11.2"
Django = "^3.1.5"

[tool.poetry.dev-dependencies]
flake8 = "^4.0.1"
black = "^22.3.0"
autopep8 = "^1.6.0"
pylint = "^2.13.9"
pylint-django = "^2.5.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
