[tool.poetry]
name = "eomap-models"
version = "0.1.15"
description = ""
authors = ["Luis Coelho"]

[tool.poetry.dependencies]
python = ">=3.7,<4.0"
pydantic = {extras = ["email"], version = "^1.9.1"}
geojson-pydantic = "0.3.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
