# coding: utf-8

"""
    Welcome to the Atera API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from atera_client.configuration import Configuration


class RateQueryDTO(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {"rate_id": "int", "amount": "float", "description": "str", "sku": "str", "category": "str"}

    attribute_map = {
        "rate_id": "RateID",
        "amount": "Amount",
        "description": "Description",
        "sku": "SKU",
        "category": "Category",
    }

    def __init__(
        self, rate_id=None, amount=None, description=None, sku=None, category=None, _configuration=None
    ):  # noqa: E501
        """RateQueryDTO - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._rate_id = None
        self._amount = None
        self._description = None
        self._sku = None
        self._category = None
        self.discriminator = None

        if rate_id is not None:
            self.rate_id = rate_id
        if amount is not None:
            self.amount = amount
        if description is not None:
            self.description = description
        if sku is not None:
            self.sku = sku
        if category is not None:
            self.category = category

    @property
    def rate_id(self):
        """Gets the rate_id of this RateQueryDTO.  # noqa: E501


        :return: The rate_id of this RateQueryDTO.  # noqa: E501
        :rtype: int
        """
        return self._rate_id

    @rate_id.setter
    def rate_id(self, rate_id):
        """Sets the rate_id of this RateQueryDTO.


        :param rate_id: The rate_id of this RateQueryDTO.  # noqa: E501
        :type: int
        """

        self._rate_id = rate_id

    @property
    def amount(self):
        """Gets the amount of this RateQueryDTO.  # noqa: E501


        :return: The amount of this RateQueryDTO.  # noqa: E501
        :rtype: float
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this RateQueryDTO.


        :param amount: The amount of this RateQueryDTO.  # noqa: E501
        :type: float
        """

        self._amount = amount

    @property
    def description(self):
        """Gets the description of this RateQueryDTO.  # noqa: E501


        :return: The description of this RateQueryDTO.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this RateQueryDTO.


        :param description: The description of this RateQueryDTO.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def sku(self):
        """Gets the sku of this RateQueryDTO.  # noqa: E501


        :return: The sku of this RateQueryDTO.  # noqa: E501
        :rtype: str
        """
        return self._sku

    @sku.setter
    def sku(self, sku):
        """Sets the sku of this RateQueryDTO.


        :param sku: The sku of this RateQueryDTO.  # noqa: E501
        :type: str
        """

        self._sku = sku

    @property
    def category(self):
        """Gets the category of this RateQueryDTO.  # noqa: E501


        :return: The category of this RateQueryDTO.  # noqa: E501
        :rtype: str
        """
        return self._category

    @category.setter
    def category(self, category):
        """Sets the category of this RateQueryDTO.


        :param category: The category of this RateQueryDTO.  # noqa: E501
        :type: str
        """

        self._category = category

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict()) if hasattr(item[1], "to_dict") else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(RateQueryDTO, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RateQueryDTO):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, RateQueryDTO):
            return True

        return self.to_dict() != other.to_dict()
