defaults:
  - /_func_: chunk
  - /preprocessor/segmenter: chunk

keep_segment: false
chunk_size: 300
chunk_overlap: false
apply_to: ${oc.select:..apply_to, text}
verbose: ${oc.select:..verbose, true}
use_batcher: ${oc.select:..use_batcher, true}
preprocessor:
  keep_segment: ${oc.select:..keep_segment, false}
  chunk_size: ${oc.select:..chunk_size, 300}
  chunk_overlap: ${oc.select:..chunk_overlap, false}
  verbose: ${oc.select:..verbose, true}
  segmenter:
    keep_segment: ${oc.select:..keep_segment, false}
    chunk_size: ${oc.select:..chunk_size, 300}
    chunk_overlap: ${oc.select:..chunk_overlap, false}
    verbose: ${oc.select:..verbose, true}  