
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-24T10:05:14-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "258109b07b24ee186fa8376adfc56b16a36a16cf",
 "version": "0.5.20"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
