
# DO NOT EDIT THIS FILE -- AUTOGENERATED BY PANTS
# Target: pants_plugins/sendwave/pants_docker:pants_docker

from setuptools import setup

setup(**{
    'author': 'compyman@compyman.net',
    'description': 'Pants Plugin to automatically generate docker images from pants targets',
    'install_requires': (
        'pantsbuild.pants.testutil<2.10,>=2.9.0rc0',
        'pantsbuild.pants<2.10,>=2.9.0rc0',
    ),
    'name': 'sendwave-pants-docker',
    'namespace_packages': (
    ),
    'package_data': {
    },
    'packages': (
        'sendwave.pants_docker',
    ),
    'version': '1.0',
})
