
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-25T08:25:16+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "c517fc5aadcbf3917165b8af84d085f979fb27cd",
 "version": "0.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
