[tool.poetry]
name = "miniops"
version = "0.1.2"
description = "python package to efficiently work with dataframes from jsonl files stored at minio/s3"
authors = ["Federico Falconieri <federico.falconieri@tno.nl>"]

[tool.poetry.dependencies]
python = "^3.6.9"
minio = "^7.1.8"
pandas = "1.1.5"
psutil = "^5.9.1"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
build = "^0.8.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
