
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-24T02:48:35+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "b3cb27ae24ebece21dd09b1a409e5b68a5243342",
 "version": "0.0.16rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
