[tool.poetry]
name = "monobloco"
version = "0.0.1"
description = "Minimalist interfaces for taca taca toco toco taca taca"
authors = ["don toco"]

[tool.poetry.dependencies]
python = "^3.7"
numpy = "^1.15"
tqdm = "^4.40.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
