[tool.poetry]
name = "multicounter"
version = "0.1.0"
description = "A simple, elegant counter with support for counting multiple things at once."
authors = ["Joseph Hale <me@jhale.dev>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pre-commit = "^2.19.0"
black = "^22.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
