name: Notebook tests

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    name: Test notebooks with nbmake
    steps:
      - uses: actions/checkout@v2

      - name: Setup ipfs
        uses: ibnesayeed/setup-ipfs@master
        with:
          ipfs_version: ^0.12
      - name: Connect to ipfs peers with our data
        shell: bash
        run: |
          export MSYS_NO_PATHCONV=1
          # web3.storage
          ipfs swarm connect /ip4/139.178.69.155/tcp/4001/p2p/12D3KooWR19qPPiZH4khepNjS3CLXiB7AbrbAD4ZcDjN1UjGUNE1
          ipfs swarm connect /ip4/139.178.68.91/tcp/4001/p2p/12D3KooWEDMw7oRqQkdCJbyeqS5mUmWGwTp8JJ2tjCzTkHboF6wK
          ipfs swarm connect /ip4/147.75.33.191/tcp/4001/p2p/12D3KooWPySxxWQjBgX9Jp6uAHQfVmdq8HG1gVvS1fRawHNSrmqW
          ipfs swarm connect /ip4/147.75.32.73/tcp/4001/p2p/12D3KooWNuoVEfVLJvU3jWY2zLYjGUaathsecwT19jhByjnbQvkj
          ipfs swarm connect /ip4/145.40.89.195/tcp/4001/p2p/12D3KooWSnniGsyAF663gvHdqhyfJMCjWJv54cGSzcPiEMAfanvU
          ipfs swarm connect /ip4/136.144.56.153/tcp/4001/p2p/12D3KooWKytRAd2ujxhGzaLHKJuje8sVrHXvjGNvHXovpar5KaKQ
          # pinata.cloud
          ipfs swarm connect /dnsaddr/fra1-1.hostnodes.pinata.cloud/p2p/QmWaik1eJcGHq1ybTWe7sezRfqKNcDRNkeBaLnGwQJz1Cj
          ipfs swarm connect /dnsaddr/fra1-2.hostnodes.pinata.cloud/p2p/QmNfpLrQQZr5Ns9FAJKpyzgnDL2GgC6xBug1yUZozKFgu4
          ipfs swarm connect /dnsaddr/fra1-3.hostnodes.pinata.cloud/p2p/QmPo1ygpngghu5it8u4Mr3ym6SEU2Wp2wA66Z91Y1S1g29
          ipfs swarm connect /dnsaddr/nyc1-1.hostnodes.pinata.cloud/p2p/QmRjLSisUCHVpFa5ELVvX3qVPfdxajxWJEHs9kN3EcxAW6
          ipfs swarm connect /dnsaddr/nyc1-2.hostnodes.pinata.cloud/p2p/QmPySsdmbczdZYBpbi2oq2WMJ8ErbfxtkG8Mo192UHkfGP
          ipfs swarm connect /dnsaddr/nyc1-3.hostnodes.pinata.cloud/p2p/QmSarArpxemsPESa6FNkmuu9iSE1QWqPX2R3Aw6f5jq4D5
      - name: Cache ipfs testing data locally
        shell: bash
        run: |
          cid=$(grep 'IPFS_CID =' test/test_multiscale_spatial_image.py | cut -d ' ' -f 3 | tr -d '"')
          ipfs get -o ./test/data -- $cid
          cid=bafybeibpqky6d335duxtkmwowcc6igt2q5qorqd7e5xqfoxlfxm4pozg74
          ipfs get -- $cid
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'zulu'
      - name: Install test dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -e ".[test]"
          python3 -m pip install pyimagej
          python3 -c "import imagej; ij = imagej.init('2.5.0'); print(ij.getVersion())"
      - name: Test notebooks
        run: |
          pytest --nbmake --nbmake-timeout=3000  examples/*ipynb
