[tool.poetry]
name = "herec"
version = "0.0.1"
description = "Actor Implementation in Python built with ZeroMQ"
authors = ["Ian Kollipara <ian.kollipara@cune.org>"]
readme = "README.md"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
pyzmq = "^23.0.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
pytest-cov = "^3.0.0"
black = "^22.3.0"
wemake-python-styleguide = "^0.16.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
