[tool.poetry]
name = "qapi-sdk"
version = "0.1.2"
description = "QAPI SDK provides a library of classes for working with Query API in your Python code."
authors = ["TheBridgeDan <97176881+TheBridgeDan@users.noreply.github.com>"]
readme = "README.md"
packages = [{ include = "qapi_sdk" }]

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.27.1"
python-dotenv = "^0.20.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
