[tool.poetry]
name = "biopsykit"
version = "0.5.1"
description = "A Python package for the analysis of biopsychological data."
authors = [
    "Robert Richer <robert.richer@fau.de>",
    "Arne Küderle <arne.kuederle@fau.de>",
    "Rebecca Lennartz <rebecca.lennartz@fau.de>",
    "Daniel Krauß <daniel.k.krauss@fau.de>",
    "Victoria Müller <victoria.m.mueller@fau.de>",
    "Martin Ullrich <martin.ullrich@fau.de>",
    "Janis Zenkner <janis.zenkner@fau.de>",
]
readme = "README.md"
homepage = "https://github.com/mad-lab-fau/biopsykit"
repository = "https://github.com/mad-lab-fau/biopsykit"
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
numpy = "^1"
pandas = "^1"
matplotlib = "^3"
seaborn = "^0.11.2"
neurokit2 = "^0.1.3"
pingouin = "^0.5.1"
scipy = "^1.7.0"
statannot = "^0.2.3"
tqdm = "^4.62.0"
joblib = "^1.1.0"
scikit-learn = "^1.0"
nilspodlib = "^3.2.2"
openpyxl = "^3.0.7"
XlsxWriter = "^1.4.5"
xlrd = "^2.0.1"
statsmodels = "^0.13"
fau-colors = "^1"
mne = {version = "^0.23.0", optional = true}
IPython = {version = "^7.13.0", optional = true}
ipywidgets = {version = "^7.6.3", optional = true}
ipympl = {version = "^0.8.0", optional = true}

[tool.poetry.extras]
mne = ["mne"]
jupyter = ["IPython", "ipympl", "ipywidgets"]

[tool.poetry.dev-dependencies]
pytest = "^6.2.1"
pytest-cov = "^2.8.1"
prospector = "^1.2.0"
black = { version="^22", extras=["jupyter", "d"] }
coverage = "^4.5.4"
ipykernel = "^6.2.0"
mypy = "^0.790"
pytest-xdist = "^2.2.0"
# Doc dependencies. They also need to be updated in ./docs/requirements.txt
sphinx = "^4.2.0"
numpydoc = "^1"
sphinx-gallery = "^0.10.0"
sphinx_issues = "^1.2.0"
pydata-sphinx-theme = "^0.6.2"
recommonmark = "^0.6.0"
toml = "^0.10.1"
memory_profiler = "^0.57.0"
coverage-badge = "^1.0.1"
isort = "^5.9.3"
sphinx-copybutton = "^0.4.0"
nbsphinx = "^0.8.7"
poethepoet = "^0.10.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
target-version = ['py38']
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | docs
    | build
    | dist
    | \.virtual_documents
    | \.ipynb_checkpoints
  )/
)
'''

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 120
skip_gitignore = true


[tool.poe.tasks]
_black = "black ."
_black_check = "black . --check"
_isort = "isort **/*.py"
_isort_check = "isort **/*.py --check-only"

# Reformat all files using black and sort import
docs = {"script" = "_tasks:task_docs"}
format = ["_black", "_isort"]
format_check = ["_black_check", "_isort_check"]
lint = "prospector"
test = "pytest --cov=biopsykit --cov-report=xml"
update_version = {"script" = "_tasks:task_update_version"}
register_ipykernel = "python -m ipykernel install --user --name biopsykit --display-name biopsykit"
default = ["format", "lint", "test"]
