name: Code coverage report

on:
  pull_request:
  push:
    branches:
    - master
    - develop

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.10"]
        os: [ubuntu-latest]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2

    - name: Setup Conda
      uses: s-weigand/setup-conda@v1
      with:
        activate-conda: false
        conda-channels: conda-forge

    - name: Python ${{ matrix.python-version }}
      shell: bash -l {0}
      run: |
        conda create --name TEST python=${{ matrix.python-version }} pip --file requirements.txt --file test_requirements.txt --strict-channel-priority
        source activate TEST
        pip install -e . --no-deps --force-reinstall

    - name: Conda Info
      shell: bash -l {0}
      run: |
        source activate TEST
        conda info --all
        conda list

    - name: Run tests with coverage
      shell: bash -l {0}
      run: |
        source activate TEST
        pytest --cov=compliance_checker --cov-report=xml compliance_checker/tests
      # pass this step even if there are individual test failures, we are
      # interested in the overall level of coverage and other checks can
      # report on test failures.
      continue-on-error: true

    - name: Upload to codecov
      uses: codecov/codecov-action@v2
      with:
        files: coverage.xml
