[build-system]
requires = [
    "setuptools",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "topological-signal-compression"
version = "0.08"
authors = [{name="Gary Koplik", email="gary.koplik@geomdata.com"}]
description = "Topological Signal Compression"
readme = "README.md"
license = {text = "GNU AGPL"}
urls = {Documentation="https://geomdata.gitlab.io/topological-signal-compression/index.html", Source="https://gitlab.com/geomdata/topological-signal-compression" }

dependencies = [
    "numpy<1.22",
    "gda-public"
]

[project.optional-dependencies]
extras = [
    "kymatio",
    "matplotlib",
    "pydub",
    "pyts"
]
testing = [
    "pytest",
    "pytest-cov",
    "pytest-html",
    "pytest-timeout",
    "pytest-xdist"
]
docs = [
    "nbsphinx",
    "sphinx",
    "sphinx-rtd-theme",
    "toml"
]

[tool.setuptools]
packages = ["tsc", "tsc.utils"]
