[tool.poetry]
name = "syringe_pumps"
version = "0.1.2"
description = "Library for the control of syringe pumps"
authors = ["Diana Arguijo"]
packages = [
    { include="syringe_pumps", from="." },
]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
