[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.towncrier]
package = "towncrier"
filename = "CHANGELOG.md"
underlines = ["-", "", ""]
template = "towncrier/template.md"
title_format = "v{version} - {project_date}"
issue_format = "[#{issue}](https://framagit.org/parisni/podcast-dl/-/issues/{issue})"
start_string = "<!-- TOWNCRIER -->"
