# Generated by Django 3.2 on 2021-10-06 18:37

from django.db import migrations, models
import rygg.api.models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_auto_20210722_0310"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataset",
            name="source_url",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="dataset",
            name="location",
            field=models.TextField(
                blank=True,
                validators=[
                    rygg.api.models.dataset.validate_path,
                    rygg.api.models.dataset.validate_file_exists,
                ],
            ),
        ),
    ]
