[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[tool.black]
skip-string-normalization = true
target-version = ['py39']

[tool.coverage.report]
omit = []

[tool.isort]
profile = "black"

[tool.mypy]
namespace_packages = true

[[tool.mypy.overrides]]
module = [
    'opentelemetry.instryumentation.distro'
]
implicit_reexport = true


[tool.pytest.ini_options]
minversion = "6.0"
addopts = """
    --black
    --flake8
    --isort
    --mypy
    --cov=src
    --cov=tests
    --cov-branch
    --cov-report=term-missing
    --cov-fail-under=87
    --no-cov-on-fail
"""
