BIG_QUERY_PROJECT = "trellatale"
READ_BIG_QUERY_PROJECT = "trell-ds-common"
WRITE_BIG_QUERY_PROJECT = "trellatale"
BIG_QUERY_SERVICE_ACCOUNT_FILE_PATH = "trell-ds-projects-common.json"
BUCKET_NAME="data-science-objects"