[tool.poetry]
name = "miniops"
version = "0.1.1"
description = ""
authors = ["Federico Falconieri <federico.falconieri@tno.nl>"]

[tool.poetry.dependencies]
python = "^3.9"
minio = "^7.1.8"
pandas = "^1.4.2"
psutil = "^5.9.1"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
tbump = "^6.9.0"
build = "^0.8.0"
twine = "^4.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
