[tool.poetry]
name = "pbt-service"
version = "5.0.0"
description = "PortalBilet service core"
authors = ["everhide <i.tolkachnikov@gmail.com>"]
packages = [
    { include = "service" },
    { include = "tests" },
]

include = [
    "env.example",
    "log.yaml",
    "i18n",
    "README.md",
]

[tool.poetry.dependencies]
python = "^3.9"
fire = "^0.4.0"
python-dotenv = "^0.20.0"
pytest = "^7.1.2"
fastapi = "^0.78.0"
uvicorn = "^0.17.6"
Pygments = "^2.12.0"
tblib = "^1.7.0"
logging-json = "^0.2.1"
PyYAML = "^6.0"
Babel = "2.10.1"
sentry-sdk = "1.5.10"
pytest-asyncio = "0.18.3"
httpx = "0.22.0"
toml = "0.10.2"
pytest-logger = "^0.5.1"
Faker = "^13.11.1"
yarl = "^1.7.2"
jsonrpcserver = "^5.0.7"
requests = "^2.27.1"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts = 'tests -p no:warnings'
asyncio_mode = 'auto'
python_files = 'test_*.py tests_*.py'
log_cli = 0
log_level = 'CRITICAL'


[i18n]
locales = [
    "ru_RU",
    "en_US",
]