[build-system]
build-backend = "setuptools.build_meta:__legacy__"
requires = ["setuptools", "wheel"]
[tool.pytest.ini_options]
addopts = "-vs" # for print statement output to console
minversion = "6.0" 
testpaths = [
  "probnode/tests",
]
