name: Upload Python Package

on:
    release:
        types: [created]

jobs:
    deploy:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v2
            - name: local-fix
              run: |
                # Hack to get setup-python to work on act
                # (see https://github.com/nektos/act/issues/251)
                if [ ! -f "/etc/lsb-release" ] ; then
                  echo "DISTRIB_RELEASE=18.04" > /etc/lsb-release
                fi
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.7"
            - name: Set up Node.js
              uses: actions/setup-node@v1
              env:
                  RUNNER_TEMP: /tmp
              with:
                  node-version: "14.x"
            - name: Install Python dependencies
              run: |
                  python -m pip install --upgrade pip wheel setuptools
                  pip install twine mkdocs mkdocs-material
            - name: Generate webpack bundle
              working-directory: ./bcml/assets
              run: |
                  npm install
                  ./node_modules/.bin/webpack --mode production
            - name: Build docs
              run: mkdocs build -d ./bcml/assets/help
            - name: Build Python packages
              run: |
                python setup.py sdist bdist_wheel
            - name: Publish to PyPI
              if: ${{ !env.ACT }}
              env:
                  TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
                  TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
              run: twine upload dist/*
