[tool.poetry]
name = "dagmate"
version = "0.1.0"
description = "Make your Dagster deployment faster and easier with Dagger"
authors = ["Anoop Sharma"]

[tool.poetry.dependencies]
python = "^3.8"
dagster = "^0.14.13"
dagit = "^0.14.13"
dagster-graphql = "^0.14.13"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
