[project]
name = "cookiecutter-rustpython"
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
]

[build-system]
requires = ["maturin>=0.12,<0.13"]
build-backend = "maturin"