site_name: Reaction-network documentation
site_description: Documentation for the reaction-network package
copyright: Built by Matthew McDermott (GENESIS-EFRC)

nav:
  - Home: index.md
  - Notebooks:
        - Enumerators: 
            - Enumerators: enumerators.ipynb
        - Network: 
            - Network: network.ipynb
  - Reference:
      - Builders:
          Retrosynthesis: reference/builders/retrosynthesis.md
      - Core:
          Calculator: reference/core/calculator.md
          Cost Function: reference/core/cost_function.md
          Enumerator: reference/core/enumerator.md
          Network: reference/core/network.md
          Pathway: reference/core/pathway.md
          Reaction: reference/core/reaction.md
          Solver: reference/core/solver.md
      - Costs:
          Calculators: reference/costs/calculators.md
          Competition: reference/costs/competition.md
          Softplus: reference/costs/softplus.md
      - Data: reference/data/data.md
      - Entries:
          Barin: reference/entries/barin.md
          Corrections: reference/entries/corrections.md
          Entry Set: reference/entries/entry_set.md
          Experimental: reference/entries/experimental.md
          Freed: reference/entries/freed.md
          Gibbs: reference/entries/gibbs.md
          Nist: reference/entries/nist.md
      - Enumerators:
          Basic: reference/enumerators/basic.md
          Minimize: reference/enumerators/minimize.md
          Utils: reference/enumerators/utils.md
      - Firetasks:
          Build Inputs: reference/firetasks/build_inputs.md
          Parse Outputs: reference/firetasks/parse_outputs.md
          Run Calc: reference/firetasks/run_calc.md
          Utils: reference/firetasks/utils.md
      - Fireworks:
          Core: reference/fireworks/core.md
      - Network:
          Entry: reference/network/entry.md
          Graph-tool: reference/network/gt.md
          Network: reference/network/network.md
          Utils: reference/network/utils.md
          Visualize: reference/network/visualize.md
      - Pathways:
          Balanced: reference/pathways/balanced.md
          Basic: reference/pathways/basic.md
          Pathway Set: reference/pathways/pathway_set.md
          Plotting: reference/pathways/plotting.md
          Solver: reference/pathways/solver.md
      - Reactions:
          Basic: reference/reactions/basic.md
          Computed: reference/reactions/computed.md
          Open: reference/reactions/open.md
          Plotting: reference/reactions/plotting.md
          Reaction Set: reference/reactions/reaction_set.md
      - Thermo:
          Chempot Diagram: reference/thermo/chempot_diagram.md
          Utils: reference/thermo/utils.md
      - Utils:
          Database: reference/utils/database.md
          Funcs: reference/utils/funcs.md
          Models: reference/utils/models.md
          Ray: reference/utils/ray.md
  - CHANGELOG: CHANGELOG.md

repo_url: https://github.com/GENESIS-EFRC/reaction-network/
site_url: https://genesis-efrc.github.io/reaction-network/
repo_name: Github

theme:
  name: material
  icon:
    logo: material/currency-sign
  features:
  - navigation.tabs
  - navigation.top
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: teal
    accent: purple

extra_css:
- css/mkdocstrings.css

markdown_extensions:
- admonition
- pymdownx.details
- pymdownx.emoji
- pymdownx.magiclink
- pymdownx.snippets:
    check_paths: true
- pymdownx.superfences
- pymdownx.tabbed
- pymdownx.tasklist

plugins:
- search
- section-index
- mkdocs-jupyter
- mkdocstrings:
    handlers:
      python:
        setup_commands:
        - import sys
        - sys.path.append("docs")
        selection:
          new_path_syntax: yes
    watch:
    - src/rxn_network
