
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-29T22:54:28+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "b7bca205947320dd52bcccad1571e213f93a5af0",
 "version": "1.0rc3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
