[tool.poetry]
name = "strangeworks-rigetti"
version = "0.2.10"
description = "Strangeworks Rigetti SDK extension"
readme = "DESCRIPTION.md"
authors = ["Strange Devs <hello@strangeworks.com>"]
license = "Apache-2.0"
packages = [
    {include = "strangeworks"},
]

[tool.poetry.dependencies]
python = ">=3.8, <3.10"
strangeworks = "^0.2.0"
pyquil="~3.1"

[tool.poetry.dev-dependencies]
black = "^22.1.0"
Flask = "^2.0.2"
pytest = "^7.0.1"

[build-system]
requires = ["poetry-core>=1.0.0", "setuptools", "wheel"]
build-backend = "poetry.core.masonry.api"
