# Generated by Django 3.0 on 2022-02-24 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0002_master_db_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='fname_a',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='master_db',
            old_name='fname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='fname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='lname_a',
        ),
        migrations.RemoveField(
            model_name='master_db',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='users',
            name='lname',
        ),
    ]
