# Generated by Django 3.0 on 2022-03-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0004_auto_20220302_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master_db',
            name='billable',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=10),
        ),
    ]
