# Generated by Django 3.0 on 2022-03-08 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0009_auto_20220308_0554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master_db',
            name='week_end_date',
        ),
        migrations.RemoveField(
            model_name='master_db',
            name='week_start_date',
        ),
    ]
