name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    # TODO: try using container (ex below) to have setup consistent with local.
    # ex at https://github.community/t/cant-set-pythonpath-appropriately-for-pytest-in-github-actions/116931/5
    # container:
    #   image: docker://manifoldai/orbyter-ml-dev:2.0 # replace name
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    # Spark setup as per https://github.com/marketplace/actions/setup-apache-spark
    - uses: actions/setup-java@v1
      with:
        java-version: '11'

    - uses: vemonet/setup-spark@v1
      with:
        spark-version: '3.1.2'
        hadoop-version: '3.2'

    - run: spark-submit --version
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r yaetos/scripts/requirements_alt.txt
    # - name: Lint with flake8
    #   run: |
    #     pip install flake8
    #     # stop the build if there are Python syntax errors or undefined names
    #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics  # TODO: uncomment when fixed
    #     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics  # TODO: uncomment when fixed
    - name: Test with pytest
      run: |
        pip install pytest
        pytest --ignore=yaetos/scripts/
    # TODO: change pytest cmdline above to "pytest tests/ --extraargs?" and find if extraargs exists that gets test running from work dir (i.e. not changing to 'tests/')
