[build-system]
requires = [
    "pdm-pep517",
]
build-backend = "pdm.pep517.api"

[project]
name = "mkdocstrings"
description = "Automatic documentation from sources, for MkDocs."
authors = [
    { name = "Timothée Mazzucotelli", email = "pawamoy@pm.me" },
]
readme = "README.md"
requires-python = ">=3.7"
keywords = [
    "mkdocs",
    "mkdocs-plugin",
    "docstrings",
    "autodoc",
    "documentation",
]
dynamic = []
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: ISC License (ISCL)",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Documentation",
    "Topic :: Software Development",
    "Topic :: Software Development :: Documentation",
    "Topic :: Utilities",
    "Typing :: Typed",
]
dependencies = [
    "Jinja2>=2.11.1",
    "Markdown>=3.3",
    "MarkupSafe>=1.1",
    "mkdocs>=1.2",
    "mkdocs-autorefs>=0.3.1",
    "pymdown-extensions>=6.3",
]
version = "0.19.0"

[project.license]
file = "LICENSE"

[project.optional-dependencies]
crystal = [
    "mkdocstrings-crystal>=0.3.4",
]
python-legacy = [
    "mkdocstrings-python-legacy>=0.2.1",
]
python = [
    "mkdocstrings-python>=0.5.2",
]

[project.urls]
Homepage = "https://mkdocstrings.github.io"
Documentation = "https://mkdocstrings.github.io"
Changelog = "https://mkdocstrings.github.io/changelog"
Repository = "https://github.com/mkdocstrings/mkdocstrings"
Issues = "https://github.com/mkdocstrings/mkdocstrings/issues"
Discussions = "https://github.com/mkdocstrings/mkdocstrings/discussions"
Gitter = "https://gitter.im/mkdocstrings/community"
Funding = "https://github.com/sponsors/mkdocstrings"

[project.entry-points."mkdocs.plugins"]
mkdocstrings = "mkdocstrings.plugin:MkdocstringsPlugin"

[tool.pdm]
package-dir = "src"
includes = [
    "src/mkdocstrings",
]
editable-backend = "editables"

[tool.pdm.version]
use_scm = true

[tool.pdm.dev-dependencies]
duty = [
    "duty>=0.7",
]
docs = [
    "markdown-callouts>=0.2.0",
    "mkdocs>=1.3",
    "mkdocs-coverage>=0.2",
    "mkdocs-gen-files>=0.3",
    "mkdocs-literate-nav>=0.4",
    "mkdocs-material>=7.3",
    "mkdocs-section-index>=0.3",
    "mkdocstrings-python>=0.5.1",
    "toml>=0.10",
]
format = [
    "autoflake>=1.4",
    "black>=21.10b0",
    "isort>=5.10",
]
maintain = [
    "git-changelog>=0.4",
]
quality = [
    "darglint>=1.8",
    "flake8-bandit>=2.1",
    "flake8-black>=0.2",
    "flake8-bugbear>=21.9",
    "flake8-builtins>=1.5",
    "flake8-comprehensions>=3.7",
    "flake8-docstrings>=1.6",
    "flake8-pytest-style>=1.5",
    "flake8-string-format>=0.3",
    "flake8-tidy-imports>=4.5",
    "flake8-variables-names>=0.0",
    "pep8-naming>=0.12",
    "wps-light>=0.15",
]
tests = [
    "docutils",
    "pygments>=2.10",
    "pytest>=6.2",
    "pytest-cov>=3.0",
    "pytest-randomly>=3.10",
    "pytest-xdist>=2.4",
    "sphinx",
]
typing = [
    "mypy>=0.910",
    "types-docutils",
    "types-markdown>=3.3",
    "types-pyyaml",
    "types-toml>=0.10",
]
security = [
    "safety>=1.10",
]

[tool.black]
line-length = 120
exclude = "tests/fixtures"

[tool.isort]
line_length = 120
not_skip = "__init__.py"
multi_line_output = 3
force_single_line = false
balanced_wrapping = true
default_section = "THIRDPARTY"
known_first_party = "mkdocstrings"
include_trailing_comma = true
