defaults:
  - stopwords: default
  - tokenize: default
  - tokenize_article: default
  - extract: default

_target_: ekorpkit.preprocessors.tokenizer.Tokenizer
normalize:
return_as_list: false
stopwords_path: ${oc.select:..stopwords_path, null}
tagset:
verbose: ${oc.select:..verbose, false}
