[tool.poetry]
name = "fyo"
version = "0.1.2"
description = "Pure syntactic sugar for filesystem tasks."
authors = ["ericmiguel <ericmiguel@id.uff.br>"]
keywords = ["filesystem", "pathlib"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/ericmiguel/fyo"

[tool.mypy]
check_untyped_defs = true
disallow_untyped_calls = true
disallow_untyped_defs = true
show_error_codes = true
warn_return_any = true

[[tool.mypy.overrides]]
module = []
ignore_missing_imports = true

[tool.poetry.dependencies]
python = ">=3.9,<4.0"

[tool.poetry.dev-dependencies]
isort = "^5.8.0"
pydocstyle = "^6.1.1"
flake9 = "^3.8.3"
pre-commit = "^2.13.0"
pytest = "6.0.0"
autoflake = "^1.4"
black = "^22.3.0"
typing-extensions = "^4.2.0"
mypy = "^0.960"

[tool.isort]
profile = "black"
force_single_line = true
atomic = true
include_trailing_comma = true
lines_after_imports = 2
lines_between_types = 1
use_parentheses = true
src_paths = ["poetry", "tests"]
filter_files = true
known_first_party = "poetry"

[tool.flake8]
max-line-length = 88
max-complexity = 10
exclude = [
    ".venv",
    ".git",
    "__pycache__",
    "*.egg-info",
    ".pytest_cache",
    ".mypy_cache"
]
ignore = [  # alertas e erros por conta do black
    "E501", # linha longa
    "E203", # espaço antes de ':'
    "E225", # sem espaço ao redor de operadores 
    "W503", # quebra de linha antes de um operador binário
    "W504"  # quebra de linha após um operador binário line
]

[tool.pydocstyle]
convention = "numpy"
add-ignore = "D401"
match = '(?!test_|tests).*\.py'  # ignora arquivos python contendo "test_" ou "tests"
match-dir = "[^\tests|.].*"  # ignora diretórios iniciados com "." ou "tests"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
