[tool.poetry]
name = "volcan"
version = "0.0.1"
description = "A modern, strongly-typed, general-purpose programming language."
authors = ["vcokltfre <vcokltfre@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]
isort = "^5.10.1"
black = "^22.3.0"
taskipy = "^1.10.2"

[tool.black]
line-length = 120

[tool.taskipy.tasks]
lint = "black . && isort --profile black ."

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
