[tool.poetry]
name = "ichika_utils"
version = "0.1.6"
description = "Asynchronous Statistics Utils for Ichika"
authors = ["No767 <73260931+No767@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/No767/Ichika-Utils"
repository = "https://github.com/No767/Ichika-Utils"
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Development Status :: 1 - Planning",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: Implementation :: CPython",
  "Intended Audience :: Science/Research",
]
include = ["license.txt"]
packages = [{ include = "ichika_utils", from = "src" }]

[tool.poetry.dependencies]
python = "^3.7,<3.11"
scipy = "^1.8.0"
pandas = "^1.4.2"
uvloop = "^0.16.0"
matplotlib = "^3.5.2"
scikit-learn = "^1.1.1"

[tool.poetry.dev-dependencies]
pre-commit = "^2.19.0"
pyinstrument = "^4.1.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
