# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"main": "core.ipynb"}

modules = ["core.py"]

doc_url = "https://codingforentrepreneurs.github.io/djangoctl/"

git_url = "https://github.com/codingforentrepreneurs/djangoctl/tree/main/"

def custom_doc_links(name): return None
