
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-26T14:18:37-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "0207cb8fdf63f6e635c9f5027977073bc3142cb6",
 "version": "v0.1.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
