[tool.poetry]
name = "polisher"
version = "2.0.3"
description = "Graph polisher is a library that helps you clean your plotly figures."
authors = ["Rodrigo da Silva"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
plotly = "^5.8.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
pytest-cov = "^3.0.0"
pytest-runner = "^6.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
