[tool.poetry]
authors = ["Francisco Del Roio <francipvb@hotmail.com>"]
description = "Generic repository patterm for python."
name = "generic-repository"
packages = [
  {include = "generic_repository"},
  {include = "generic_repository/py.typed"},
]
readme = "README.md"
version = "1.2a1"

[tool.poetry.dependencies]
SQLAlchemy = {version = "^1.4.0", optional = true}
httpx = {version = "^0.23.0", optional = true}
pydantic = {version = "^1.9.0", optional = true}
python = "^3.10"

[tool.poetry.dev-dependencies]
SQLAlchemy = {version = "^1.4", extras = ["aiosqlite", "mypy"]}
anyio = "^3.5.0"
autoflake = "^1.4"
bandit = "^1.7.4"
black = "^22.3.0"
devtools = "^0.8.0"
factory-boy = "^3.2.1"
fastapi = "^0.78.0"
flake8 = "^4.0.1"
isort = "^5.10.1"
mypy = "^0.950"
pydantic = "^1.9.0"
pytest = "^7.1.2"
pytest-cov = "^3.0.0"
httpx = "^0.23.0"

[tool.poetry.extras]
http = ["httpx"]
pydantic = ["pydantic"]
sqlalchemy = ["SQLAlchemy"]

[[tool.poetry.source]]
name = "aws"
url = "https://imcreate-128983747618.d.codeartifact.us-east-1.amazonaws.com/pypi/python-packs/"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool.mypy]
follow_imports = "skip"
ignore_missing_imports = true
plugins = [
  "pydantic.mypy",
  "sqlalchemy.ext.mypy.plugin",
]
strict_optional = true

[tool.isort]
known_first_party = ['app']
profile = 'black'
