# Generated by Django 3.2 on 2022-02-08 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_auto_20220113_1326"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="owner",
            field=models.CharField(default="any", max_length=1000),
        ),
        migrations.AlterField(
            model_name="project",
            name="owner",
            field=models.CharField(max_length=1000),
        ),
    ]
