
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-16T08:49:51-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "f78d199fa63cf3a439ab1399b317412ed05b122c",
 "version": "2022.5.23"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
