# Generated by Django 3.2.3 on 2022-05-18 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Driverjs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverstep',
            name='position',
            field=models.CharField(blank=True, help_text='Position of the popover', max_length=200, null=True),
        ),
    ]
