# Generated by Django 3.2.12 on 2022-02-05 14:49

from django.db import migrations


def add_settings(apps, schema_editor):
    IndyDashConfiguration = apps.get_model(
        'indydash', 'IndyDashConfiguration')

    # StructureLostShields
    IndyDashConfiguration.objects.create()


class Migration(migrations.Migration):

    dependencies = [
        ('indydash', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_settings)
    ]
