
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-24T15:56:42+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "f6828eb39deeae77943f5f4b43a292d8a8be15e9",
 "version": "v2.4.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
