[tool.poetry]
name = "treat"
version = "0.1.0"
description = "Delicious tests for Python"
authors = ["Sébastien Eustace <sebastien@eustace.io>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
pytest = "^6.2.5"
pprintpp = "^0.4.0"
cleo = "^1.0.0a3"
coverage = "^6.2"

[tool.poetry.group.dev.dependencies]
freezegun = "^1.1.0"
black = "^21.11b1"
isort = "^5.10.1"
pre-commit = "^2.2.0"
tox = "^3.21.4"

[tool.poetry.plugins."pytest11"]
treat = "treat.pytest.plugin"

[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
force_single_line = true
atomic = true
lines_after_imports = 2
lines_between_types = 1

known_first_party = "treat"
known_third_party = ["clikit", "pprintpp", "pytest", "_pytest", "pluggy"]

[build-system]
requires = ["poetry-core>=1.0.0a5"]
build-backend = "poetry.core.masonry.api"
