[tool.poetry]
authors = ["niwla23 <alwin@cloudserver.click>"]
description = ""
name = "smartinput_ng_daemon"
packages = [{include = "smartinput"}]
version = "0.2.0"

[tool.poetry.dependencies]
Flask = "^2.1.2"
Pillow = "^9.1.1"
PyAutoGUI = "^0.9.53"
PyYAML = "^6.0"
pyserial = "^3.5"
python = "^3.7"
requests = "^2.27.1"
sacn = "^1.8.1"

[tool.poetry.dev-dependencies]
autopep8 = "^1.6.0"
pytest = "^7.1.1"

[tool.poetry.scripts]
smartinput_ng_daemon = 'smartinput:run'

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
