[package]
name = "fastbloom-rs"
version = "0.1.0"
edition = "2021"
authors = ["Yan Kun <1939810907@qq.com>"]
description = "A fast bloom filter implemented by Rust for Python!"
documentation = "https://github.com/yankun1992/fastbloom"
readme = "../README.md"
homepage = "https://github.com/yankun1992/fastbloom"
repository = "https://github.com/yankun1992/fastbloom"
license-file = "../LICENSE"
keywords = ["bloom-filter"]
categories = ["bloom-filter"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit-vec = "0.6.3"
fastmurmur3 = "0.1.2"