# AutoTransform
# Large scale, component based code modification library
#
# Licensed under the MIT License <http://opensource.org/licenses/MIT>
# SPDX-License-Identifier: MIT
# Copyright (c) 2022-present Nathan Rockenbach <http://github.com/nathro>

# A sample workflow that can be used by a repo on Github to run AutoTransform
# using github actions. Usable with the GithubRemote runner for triggering
# remote runs.

name: Run AutoTransform

on:
  workflow_dispatch:
    inputs:
      schema:
        description: "A JSON encoded schema to run"
        required: true
        type: string

permissions:
  contents: write

jobs:
  run-autotransform:
    runs-on: ubuntu-latest
    name: Run
    steps:
    - uses: actions/checkout@v2
    - name: Set up git user
      # It is highly recommended to create a bot name/email to represent automated runs
      run: |
        git config --global user.name "<<BOT NAME>>"
        git config --global user.email "<<BOT EMAIL>>"
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install AutoTransform
      run: pip install AutoTransform
    # Optionally install any custom components needed
    - name: Install custom components
      run: # Install your custom components here
    - name: Run AutoTransform
      run: autotransform run --environment AUTO_TRANSFORM_SCHEMA
      env:
        AUTO_TRANSFORM_CONFIG: environment
        AUTO_TRANSFORM_CREDENTIALS_GITHUB_TOKEN: ${{ secrets.AUTO_TRANSFORM_BOT_GITHUB_TOKEN }}
        AUTO_TRANSFORM_SCHEMA: ${{ github.event.inputs.schema }}
        # List your custom components, leave off if not using any
        AUTO_TRANSFORM_IMPORTS_CUSTOM_COMPONENTS: <<custom.component.modules>>