[tool.poetry]
name = "pybuildtools"
version = "0.4.13"
description = "A set of tools for putting together buildscripts and other CLI applications"
authors = ["Rob Nelson <nexisentertainment@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://gitlab.com/N3X15/python-build-tools"
repository = "https://gitlab.com/N3X15/python-build-tools.git"
packages = [
    { include = 'buildtools' }
]

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
colorama = "^0.4.4"
Jinja2 = "3.1.2"
psutil = "^5.9.1"
lxml = "^4.8.0"
pygit2 = "^1.9.1"
requests = "^2.27.1"
"ruamel.yaml" = "^0.17.21"
six = "^1.16.0"
toml = "^0.10.2"
tqdm = "^4.64.0"
Twisted = {version = "^22.4.0", optional = true}
PyQt5 = {version = "^5.15.6", optional = true}
Nuitka = {version = "^0.8.1", optional = true}
MarkupSafe = "^2.1.1"

[tool.poetry.dev-dependencies]
build = "^0.8.0"
isort = "^5.10.1"
mypy = "^0.950"
pytest = "^7.1.2"
twine = "^4.0.0"
poetryup = "^0.7.1"
autopep8 = "^1.6.0"
types-requests = "^2.27.27"

[tool.poetry.extras]
twisted = ["Twisted"]
pyqt5 = ["PyQt5"]
nuitka = ["Nuitka"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.autopep8]
max_line_width = 200
ignore = ['E6']

[tool.isort]
max_line_width = 200