# https://python-poetry.org/

[tool.poetry]
name = "pydamain"
version = "0.7.3"
description = "도메인 주도 설계 라이브러리."
license = "Apache-2.0"
authors = ["Jongbeom-Kwon <bolk9652@naver.com>"]
readme = "README.md"
repository = "https://github.com/by-Exist/pydamain"

[tool.poetry.dependencies]
python = "^3.10"
typing-extensions = "^4.2.0"

[tool.poetry.extras]

[tool.poetry.dev-dependencies]
black = "^22.3.0"
pytest = "^7.1.2"
pytest-asyncio = "^0.18.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
