[tool.poetry]
name = "fa_singer_io"
version = "1.2.0"
description = "Singer io SDK with strict types"
authors = ["Product Team <development@fluidattacks.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
fa-purity = "^1.8.0"
Deprecated = "^1.2.12"
jsonschema = "^3.2.0"
pyRFC3339 = "^1.1"
pytz = "^2021.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
