[tool.poetry]
name = "tdsql"
version = "0.0.3"
description = "Minimum test flamework for sql"
authors = ["dr666m1 <skndr666m1@gmail.com>"]
readme = "README.md"

[tool.poetry.scripts]
tdsql = "tdsql.command:main"

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
PyYAML = "^6.0"
google-cloud-bigquery = {version = "^3.1.0", optional = true}
db-dtypes = {version = "^1.0.1", optional = true}
pandas = "^1.4.2"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
mypy = "^0.950"
types-PyYAML = "^6.0.7"
pandas-stubs = "^1.2.0"
google-cloud-bigquery = {version = "^3.1.0", optional = false}
db-dtypes = {version = "^1.0.1", optional = false}
black = "^22.3.0"
flake8 = "^4.0.1"

[tool.poetry.extras]
bigquery = ["google-cloud-bigquery", "db-dtypes"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
