:global:
  componentName: {{ cookiecutter.name }}
  feature_goldenTests: {% if cookiecutter.add_golden == "y" %}true{% else %}false{% endif %}
{%- if cookiecutter.add_matrix == "y" %}
  testMatrix:
    key: instance
    entries:
      - defaults

{%- endif %}

docs/antora.yml:
  name: {{ cookiecutter.slug }}
  title: {{ cookiecutter.name }}
{%- if cookiecutter.add_matrix == "y" %}

.github/workflows/test.yaml:
  test_makeTarget: test -e instance={% raw %}${{ matrix.instance }}{% endraw %}
{%- if cookiecutter.add_golden == "y" %}
  goldenTest_makeTarget: golden-diff -e instance={% raw %}${{ matrix.instance }}{% endraw %}
{%- endif -%}
{% endif %}
