
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-23T10:27:03-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "fbf93162f0b160d57afbf11cd7373a80d580f30a",
 "version": "3.1.19"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
