
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-30T04:13:30+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "49b917c91b4ac9534010ff62fc0ebca74b68ab9a",
 "version": "1.16.0.post.dev563"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
