
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-30T05:29:41+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "04178da1ff2659943cf3f179c880173b85a70c27",
 "version": "1.16.0.post.dev572"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
