[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "mfhm"
version = "0.1.1"
authors = [{name = "MangFu", email = "2560782597@qq.com"}]
description = "HTTP microservice package based on FastAPI and HTTPX"
readme = "README.md"
license = {file = "LICENSE"}
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3"
]
requires-python = ">=3.6.1"
dependencies = [
    "httpx==0.22.0",
    "fastapi==0.75.2",
    "uvicorn[standard]"
]

[project.urls]
Home = "https://github.com/mangfu26/mfhm"
