
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "dc125fc7f08fa6e7bfceaaa4e65005da2998dd0f",
 "version": "2022.05.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
