
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-25T03:01:35+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "bfa3a5edb78e7e8f1e373ba1a51acfbb157fb49d",
 "version": "0.2.2.post0.dev36"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
