_target_: ekorpkit.models.sentiment.lexicon.Lexicon
name: 
fullname:
source: 
lang: 
ngram_delim:
ngram_max_n:
postag_delim: /
lexicon_path: ${dir.resource}/lexicons
lexicon_features:
word_key: 
ignore_pos: false
postag_length: 
analyze:
  features:
  ngram_distiance_tolerance: 0
  ngram_delim: ${..ngram_delim}
verbose: ${oc.select:..verbose, true}
