[tool.poetry]
name = "ctnas"
version = "0.2.0"
description = ""
authors = [
    "Julian Stier <julian.stier@uni-passau.de>"
]
license = "MIT"

include = [
    "pyproject.toml",
    "README.md"
]

readme = "README.md"

homepage = "https://github.com/innvariant/ctnas"
repository = "https://github.com/innvariant/ctnas"

keywords = ["neural architecture search", "hidden structural prior", "automated machine learning", "neural network structure", "neural graph"]

[tool.poetry.dependencies]
python = "^3.8"
networkx = "^2.7.1"
s3fs = "^2022.2.0"
pandas = "^1.4.1"
joblib = "^1.1.0"
deepstruct = "~0.8.0"


[tool.poetry.dev-dependencies]
black = { version = "^20.8b1", python = "^3.6" }
pre-commit = "^2.3.0"
pytest = "^3.0"
mkdocs = "^1.1.2"
matplotlib = "^3.5.1"
seaborn = "^0.11.2"

[tool.isort]
profile = "black"
line_length = 88
force_single_line = true
atomic = true
include_trailing_comma = true
lines_after_imports = 2
lines_between_types = 1
multi_line_output = 3
use_parentheses = true
filter_files = true
src_paths = ["ctnas", "tests"]
skip_glob = ["*/setup.py", "res/", "examples/"]
known_first_party = "ctnas"
known_third_party = ["pytest", "torch" ]

[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | res
  | build
  | dist
  | tests/cache/
  | tests/.*/setup.py
)/
'''

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
