
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-30T10:08:45+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "5e8a185d2f0d22244a516633c05930159fdd8f58",
 "version": "1.16.0.post.dev578"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
