
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-24T19:26:27+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "41832f6e61de72dc9db3a2b0a00ca97153f97ebe",
 "version": "0.2.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
