[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "multiscale_spatial_image"
author = "Matt McCormick"
author-email = "matt.mccormick@kitware.com"
home-page = "https://github.com/spatial-image/multiscale-spatial-image"
classifiers = [ "License :: OSI Approved :: Apache Software License",]
description-file = "README.md"

requires = [
    "numpy",
    "dask",
    "xarray",
    "xarray-datatree>=0.0.5",
    "spatial_image>=0.2.1",
]

[tool.flit.metadata.requires-extra]
test = [
    "itk-filtering>=5.3rc4",
    "dask_image",
    "jsonschema",
    "pytest",
    "pytest-mypy",
    "fsspec",
    "ipfsspec",
    "nbmake",
    "zarr",
]

[tool.black]
line-length = 88
