[tool.poetry]
name = "sumo_output_parsers"
version = "0.6"
description = "Fast and lightweight file parsers for SUMO(traffic simulator) output"
authors = ["Kensuke Mitsuzawa <kensuke.mit@gmail.com>"]
maintainers = ["Kensuke Mitsuzawa <kensuke.mit@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7,<3.10"
dataclasses = "*"
nptyping = "^1.4.1"
numpy = "^1.19.2"
scikit-learn = "^1.0"
scipy = "*"
Cython = "*"
tabulate = "*"
pandas = "^1.1.3"
tqdm = "^4.61.2"
more_itertools = "*"
requests = "*"
joblib = "*"
lxml = "*"
h5py = "^3.1.0"

hvplot = {version = "^0.7.3", optional = true}
moviepy = { version = "<1.0.2", optional = true }
Shapely = { version = "^1.7.0", optional = true }
pyproj = { version = "^3.0.0", optional = true }
SumoNetVis = { version = "^1.6.0", optional = true }
geopandas = { version = "^0.10.0", optional = true }
geoviews = { version = "^1.9.1", optional = true }
imageio-ffmpeg = { version = "*", optional = true }
pyviz = { version = "*", optional = true }
adjustText = { version = "*", optional = true }

[tool.poetry.dev-dependencies]
pytest = "^6.2.3"
pytest-resource-path = "^1.3.0"
nbmake = "0.5"
pytest-parallel = "*"
sphinx = "*"

[tool.poetry.scripts]

[build-system]
requires = ["setuptools", "poetry", "poetry_core>=1.0", "cython"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.extras]
full = ["Shapely", "pyproj", "adjustText", "SumoNetVis", "geopandas",
    "geoviews", "imageio-ffmpeg", "pyviz", "moviepy", "hvplot"]
