[tool.poetry]
name = "fshasher"
version = "0.1.0"
description = "Cross-platform file-object hasher"
authors = ["Matias Grioni <matgrioni@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
