[tool.poetry]
name = "primapy-hub"
version = "0.1.0"
description = "Ptyhon Knative based Hub library"
authors = ["Team AMOps <amops@prima.it>"]
repository = "https://github.com/primait/primapy-hub"

[[tool.poetry.source]]
name = 'PyPI'
url = 'https://pypi.org/simple/'
default = true

[[tool.poetry.source]]
name = 'artifactory'
url = 'https://prima.jfrog.io/artifactory/api/pypi/primapy/simple'
secondary=true

[tool.poetry.dependencies]
python = "3.8"
fastapi = "^0.68.1"
primapy = "^0.9.3"
primapy-koffing = {version = "^0.2.1", source = "artifactory", extras = ["yaml"]}
primapy-plogging = {version = "^0.2.0", source = "artifactory"}
primapy-tracing = {version = "^0.3.0", extras = ["fastapi", "aiohttp"], source = "artifactory"}
uvicorn = {version = "^0.17.6", extras = ["standard"]}

[tool.poetry.dev-dependencies]
asynctest = "^0.13.0"
black = "^22.3"
isort = "^5.10.1"
mockumentary = {version = "0.1.1", source = "artifactory"}
mypy = "^0.950"
pre-commit = "^2.15.0"
pylint = "^2.13.0"
pytest = "^7.1.2"
pytest-asyncio = "^0.18.0"
pytest-cov = "^3.0.0"
pytest-mock = "^3.7.0"
pytest-xdist = "^2.5.0"
types-toml = "^0.10.7"

[tool.pylint.BASIC]
min-public-methods = 0
    [tool.pylint."MESSAGES CONTROL"]
    persistent = "no"
    max-line-length = 120
    disable = [
        "duplicate-code",
        "missing-module-docstring",
        "fixme",
    ]
    extension-pkg-whitelist = "pydantic"

[tool.isort]
profile = "black"

[tool.black]
line-length = 120

[tool.mypy]
strict = true
pretty = true
show_error_codes = true
show_error_context = true
implicit_reexport = true
namespace_packages = true

    [[tool.mypy.overrides]]
    ignore_missing_imports = true

    [[tool.mypy.overrides]]
    # No type stubs available
    module = "primapy_plogging.*"
    ignore_missing_imports = true    
    
    [[tool.mypy.overrides]]
    # No type stubs available
    module = "pytest.*"
    ignore_missing_imports = true

    [[tool.mypy.overrides]]
    # No type stubs available
    module = "ruamel.*"
    ignore_missing_imports = true

    [[tool.mypy.overrides]]
    module = "tests.*"
    disallow_incomplete_defs = false
    disallow_untyped_defs = false

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
