[tool.poetry]
name = "nextup"
version = "0.1.0"
description = "Next Up your Next Install"
authors = ["VincentRPS"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
click = "^8.1.3"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
isort = "^5.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
