
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-24T12:17:06+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "f8816db51b459d19745634d511356965ad2cd88b",
 "version": "0.2.47"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
