[tool.poetry]
name = "watchmen-ml-python-sdk"
version = "0.1.2"
description = ""
authors = ["luke0623 <luke0623@outlook.com>"]

packages = [
    { include = "ml_sdk"}
]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.27.1"
pandas = "^1.4.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
