
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-30T04:58:43+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "292ccb557da7599c363aead43c1856076dc617a6",
 "version": "1.16.0.post.dev569"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
