[build-system]
requires = ["setuptools>=43", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = ["tests/unit"]

[tool.coverage.run]
branch = true
source = ["hijri_converter"]

[tool.coverage.paths]
source = ["src"]

[tool.black]
line-length = 80
target-version = ["py36", "py37", "py38", "py39", "py310"]

[tool.isort]
profile = "black"

[tool.pylint.messages_control]
disable = ["bad-whitespace", "bad-continuation"]  # recommended by Black

[tool.pylint.reports]
score = false

[tool.pylint.format]
max-line-length = 80
expected-line-ending-format = "LF"

[tool.pylint.master]
py-version = "3.6"

[tool.mypy]
python_version = "3.6"
strict = true

[tool.taskipy.tasks]
test = "task test_cov tests"
test_cov = "pytest --cov --cov-report=term-missing --cov-fail-under=100"
test_cov_html = "pytest --cov --cov-report=term --cov-report=html"
test_all = "pytest tests"
lint = "task lint_isort && task lint_black && task lint_pylint && task lint_mypy"
lint_isort = "isort --check-only src tests"
lint_black = "black --check --quiet src tests"
lint_pylint = "pylint src"
lint_mypy = "mypy src"
format = "isort src tests && black src tests"
upgrade = "task upgrade_dev && task upgrade_docs"
upgrade_dev = "pip install -U -r requirements-dev.txt"
upgrade_docs = "pip install -U -r docs/requirements.txt"
docs = "sphinx-build -E docs docs/_build"
