
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-25T14:53:02+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "f91a528f06bde1dfa6c550ed6fea4e63b609d935",
 "version": "0.4.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
