
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-27T08:58:17+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "b0b15928b4a20fa0c67d7b10a1d0937c1827c289",
 "version": "0.13.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
