[tool.poetry]
name = "memorable"
version = "1.0.3"
license = "MIT"
repository = "https://gitlab.com/kjschiroo/memorable"
description = "A library for creating memorable strings."
authors = ["Kevin Schiroo <kjschiroo@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
watchdog = "^2.1.0"
pytest-cov = "^2.11.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
