[tool.poetry]
name = "json_de2zh"
version = "0.1.1"
description = "pack_name descr "
authors = ["ffreemt"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/ffreemt/json-de2zh"

[tool.poetry.dependencies]
python = "^3.8.3"
icecream = "^2.1.1"
install = "^1.3.5"
rich = "^12.4.1"
set-loglevel = "^0.1.2"
alive-progress = "^2.4.1"
joblib = "^1.1.0"
typer = "^0.4.1"
nltk = "^3.7"
numpy = "^1.22.3"
sklearn = "^0.0"
fastlid = "^0.1.7"
simplemma = "0.3.0"
fast-scores = "^0.1.2"
cmat2aset = "^0.1.0-alpha.7"
split-words = "^0.1.2"

[tool.poe.executor]
type = "poetry"

[tool.poe.tasks]
memo = "echo poe test or poetry run poe test"
pyright = "pyright json_de2zh"
test = "pytest tests"
build = "poetry build"
_publish = "poetry publish"
release = ["test", "build", "_publish"]
lint = { cmd = "pylint json_de2zh" }
format = "black tests json_de2zh"
docstyle = "pydocstyle --convention=google tests json_de2zh"
tunnel = {cmd = "ssh -CN ip_or_hostname_defined_in_hosts -L 9091:127.0.0.1:9091"}

[tool.poetry.dev-dependencies]
pytest = "^7.1"
flake8 = "^3.9.2"
pydocstyle = "^6.1.1"
toml = "^0.10.2"
# tbump = "^6.3.2"
poethepoet = "^0.10.0"

[tool.poetry.scripts]
"json-de2zh" = "json_de2zh.__main__:app"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q --doctest-modules"
log_cli = true
testpaths = [
    "tests",
    # "integration",
]

[tool.black]
skip-string-normalization = 0

[tool.isort]
profile = "black"
multi_line_output = 3
