[build-system]
requires = [
    "setuptools>=42",
    "django>=2.2.27",
    "Pillow>=8.0.1",
    "djangorestframework>=3.13.1",
    "django-import-export>=2.7.1",
]
build-backend = "setuptools.build_meta"