name: Python Package using Conda for rc branch

on:
  push:
    branches:
    - rc

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda install --yes -c conda-forge python=${{ matrix.python-version }}
        conda install --yes -c conda-forge matplotlib-base pyyaml openblas gcc_linux-64 h5py scipy pytest codecov pytest-cov spglib alm
        pip install https://github.com/phonopy/phonopy/archive/rc.zip --user
    - name: Set up phono3py
      run: |
        export CONDA_PREFIX=$CONDA
        echo "[phono3py]" > site.cfg
        echo "extra_compile_args = -fopenmp" >> site.cfg
        echo "extra_link_args = -lgomp" >> site.cfg
        python setup.py build
        pip install -e .
    - name: Test with pytest
      run: |
        pytest --cov=./ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        verbose: true
