[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "boa"
dist-name= "bws-boa"
author = "Jose Angel Delgado"
author-email = "esojangel@gmail.com"
description-file = "README.md"
requires=[
    "werkzeug==0.16.1",
    "flask==1.1.1",
    "click>=8.0.1",
    "flask-admin>=1.5.8",
    #"flask-script>=2.0.6",
    "Flask-SQLAlchemy>=2.4.1",
    "Flask-Migrate==2.5.2",
    "flask-babel>=0.12.2",
    "itsdangerous==2.0.1",
    "jinja2==3.0.1",
    "markupsafe==2.0.1",
    "requests>=2.26.0",
    "wtforms==2.3.3",
    "pytz==2021.1",
    "SQLAlchemy>=1.3.11",
    "python-dotenv>=0.18.0",
    "PyMySQL>=0.9.3",
]
requires-python=">=3.6"
classifiers=[
    "License :: OSI Approved :: Apache Software License",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    'Programming Language :: Python :: 3.6',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[tool.flit.scripts]
boa = "boa.cmd:boa_cli"
bws = "boa.cmd:boa_cli"

[tool.flit.sdist]
include = [
    # "boa/*.json",
    "boa/package.json",
    "boa/plopfile.js",
    "boa/plop-templates/*.hbs",
]
exclude = []