# coding: utf-8
# Generated by setup.py for PyCBC on 2022-05-26 12:30:14 +0000.

version = '2.0.3'
date = '2022-05-26 12:05:59 +0000'
release = True
last_release = '2.0.3'

git_hash = '8ab8abc409fa7800643b1ef45ab19fca98cd3229'
git_branch = 'None'
git_tag = 'v2.0.3'
git_author = 'Alex Nitz <alex.nitz@gmail.com>'
git_committer = 'GitHub <noreply@github.com>'
git_status = 'CLEAN: All modifications committed'
git_builder = 'Unknown User <>'
git_build_date = '2022-05-26 12:30:14 +0000'
git_verbose_msg = """Version: 2.0.3
Branch: None
Tag: v2.0.3
Id: 8ab8abc409fa7800643b1ef45ab19fca98cd3229
Builder: Unknown User <>
Build date: 2022-05-26 12:30:14 +0000
Repository status is CLEAN: All modifications committed"""
from pycbc._version import *
