# Copyright (c) 2021 Grumpy Cat Software S.L.
#
# This Source Code is licensed under the MIT 2.0 license.
# the terms can be found in LICENSE.md at the root of
# this project, or at http://mozilla.org/MPL/2.0/.
from enum import Enum


class AttributeNames(Enum):
    ALLOW_MULTI_SELECTION = "allowMultiSelection"
    BINS = "bins"
    CATEGORIES = "categories"
    COLLECTION_ID = "collectionId"
    COL = "col"
    COL_SPAN = "colSpan"
    COLOR = "color"
    CUMULATIVE = "cumulative"
    DATA = "data"
    DATE = "date"
    DEFAULT = "default"
    DISABLED = "disabled"
    DRAGGABLE = "draggable"
    END_DATE = "endDate"
    EVENTS = "events"
    EVERY = "every"
    GROUPS = "groups"
    FORMAT = "format"
    HIDDEN = "hidden"
    ID = "id"
    INDEX_BY = "indexBy"
    INPUT_FILTERS = "inputFilters"
    LABEL = "label"
    LABEL_BY = "labelBy"
    LANE_INDEX = "laneIndex"
    MAX = "max"
    MAX_DATE = "maxDate"
    METADATA_FIELDS = "metadataFields"
    MIN = "min"
    MIN_DATE = "minDate"
    NAME = "name"
    NDARRAY = "NDArray"
    NUM_COLS = "numCols"
    NUM_ROWS = "numRows"
    OFFSET = "offset"
    OPERATION = "widget-initializer"
    OPTIONS = "options"
    OUTPUT_WIDGET = "outputWidgets"
    PLACEHOLDER = "placeholder"
    PLACEMENTS = "placements"
    PLOTS = "plots"
    POINTS = "points"
    PROPERTIES = "properties"
    RANGE = "range"
    REF = "$ref"
    RESIZABLE = "resizable"
    ROW = "row"
    ROW_SPAN = "rowSpan"
    TIME_FORMAT = "timeFormat"
    SEQUENCE = "sequence"
    SEQUENCE_ID = "sequenceId"
    SIZE = "size"
    START_DELAY = "startDelay"
    START_DATE = "startDate"
    STEP = "step"
    TABS = "tabs"
    TEXT = "text"
    TIMES = "times"
    TITLE = "title"
    TREND_LINE = "trendLine"
    TYPE = "type"
    TYPE_NOT_SUPPORTED = "only supports int/float types"
    VALUE = "value"
    VALUE_BY = "valueBy"
    VALUES = "values"
    VIEWS = "views"
    WIDGET = "widget"
    WIDGETS = "widgets"
    WIDGET_REF = "widgetRef"
    WIDTH = "width"
    X = "x"
    X_AXIS = "xAxis"
    Y_AXIS = "yAxis"
    Z_AXIS = "zAxis"
