[tool.poetry]
name = "pysaql"
version = "0.11.0"
description = "Python SAQL query builder"
authors = ["Jonathan Drake <jon.drake@salesforce.com>"]
license = "BSD-3-Clause"
readme = "README.md"
homepage = "https://github.com/NarrativeScience/pysaql"
repository = "https://github.com/NarrativeScience/pysaql"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pre-commit = "^2.10.1"
pytest = "^6.2.2"
black = "^22.3.0"
cruft = "^2.9.0"
flake8 = "^4.0.1"
mypy = ">=0.942,<1"

[tool.cruft]
skip = ["pyproject.toml", "pysaql", "tests", "README.md", ".circleci/config.yml"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
