[build-system]
requires = ["flit_core >=3.2"]
build-backend = "flit_core.buildapi"

[project]
name = "xarray_behave"
dist-name = "xarray-behave"
module = "xarray_behave"
author = "Jan Clemens"
author-email = "clemensjan@googlemail.com"
home-page = "https://github.com/janclemenslab/xarray-behave"
classifiers = ["License :: OSI Approved :: MIT License"]
dynamic = ["version", "description"]
requires-python = ">3.6"
requires = ['numpy', 'scipy', 'xarray', 'h5py', 'zarr', 'flammkuchen',
            'dask', 'toolz', 'samplestamps', 'pysoundfile', 'opencv-python-headless']
# description-file = "README.md"

[project.requires-extra]
gui = ['pyside6', 'pyqtgraph>0.12.2', 'pyvideoreader', 'qtpy',
       'sounddevice', 'scikit-image', 'pyyaml', 'defopt', 'colorcet',
       'peakutils']

[project.scripts]
xb = "xarray_behave.gui.app:cli"

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = ["tests",]
