
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-27T16:17:29-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "b4a8a2c37b173617cbc3c949787437fe50968c6f",
 "version": "22.0.0rc0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
