# This file is generated by setup.py. DO NOT EDIT!
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals
version = '0.9.7'
git_version = '78025bd9b57243515836ceea5307ee206a4f0dc6'
